name: QuickBoard
author: The_TadeSK
version: 4.2.1
main: me.tade.quickboard.QuickBoard
softdepend: [PlaceholderAPI, MVdWPlaceholders]
commands:
   quickboard:
      aliases: [qb, board, quickb, qbr, gbd]